server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/rag_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:}
      chat:
        options:
          model: ${AI_DASHSCOPE_CHAT_MODEL:qwen-plus}
          temperature: ${AI_DASHSCOPE_TEMPERATURE:0.0}
      embedding:
        options:
          model: ${AI_DASHSCOPE_EMBEDDING_MODEL:text-embedding-v4}
          dimensions: ${AI_DASHSCOPE_EMBEDDING_DIMENSIONS:1024}
